### ISSUE TITLE
Storage::S3::Error: Configuration Error

### ISSUE THREAD

**Issue by rachitgarg** [meskyanichi/backup#545]
Whenever I run my backup I get this error "#access_key_id, #secret_access_key, #bucket are all required"

my model looks like this-
```ruby
Backup::Model.new(:bkp, 'Backup') do
    database PostgreSQL do |db|
        db.name               = APP_DB_CONFIG['database']
        db.username           = APP_DB_CONFIG['username']
        db.password           = APP_DB_CONFIG['password']
        db.host               = APP_DB_CONFIG['host']
        db.port               = APP_DB_CONFIG['port']
    end
    store_with S3, storage_id do |s3|
        s3.access_key_id     = "*********"
        s3.secret_access_key = "*************"
        s3.keep              = 10
        s3.region            = "us-east-1"
        s3.bucket            = "test-bucket"
        s3.path              = "/daily"
     end
    compress_with Gzip
end 
```

Any help in this ??
Also, if I use s3.use_iam_profile=true then it says "ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
"...

**Comment by emir93795** [comment]
I know that this "issue" seems to be close by now, but I was facing the same problem with Backup and after hours I found which the problem was....

I have more than one model using S3. One of them had the bad configuration... and so the backup was not able to initiate correctly.

Hope this will help someone
