### ISSUE TITLE
Archive for each directory

### ISSUE THREAD

**Issue by Twiebie** [meskyanichi/backup#628]
Is it possible to create an archive for each directory in a one backup run?

For example if I want to backup all websites that are in /srv.

Instead of having one archive with all directories in them, is it possible to have an archive for each directory in /srv?

Awesome tool, btw!

**Comment by tombruijn** [comment]
Hi @Twiebie. Without actually making a different backup model configuration this is currently not possible. The entire contents of the backup is added to one archive file. This is by design, so incremental backups can be made and they can be easily deleted by deleting the one single file of that backup.

So set up another configuration and call this separately to create a separate archive for this directory.

Let me know if you need more information

**Comment by Twiebie** [comment]
Are there any plans to implement such functionality?

Both for files and databases it would be really nice to be able to dump them in their own archives without having to specify a separate model for each one.

I'm currently doing something like this for the folders, but it's far from optimal as it basically just creates one huge archive.

```ruby
Dir['/srv*'].each do |path|
  archive :websites do |archive|
    archive.add path
    archive.tar_options '--warning=no-file-changed --warning=no-file-removed'
  end
end
```

**Comment by tombruijn** [comment]
@Twiebie there are no plans currently to add such a feature. You can submit feature requests on the feature issue tracker. This list will be used to see what features can be (easily) added in the next major version of backup. Things we can keep in mind while (re)writing it.

If you want this soon I suggest creating a PR implementing this feature on a single model basis. The team is not going to add any new features to this version of backup.
