### ISSUE TITLE
Ability to change timestamp timezone and format.

### ISSUE THREAD

**Issue by JimmySticks2001** [meskyanichi/backup#641]
Hopefully this is a simple feature request. It would be nice if there was the ability to change the timezone that is used to create the timestamp for the logs and the folders as well as being able to change the format for the timestamp. Something along the lines of Ruby's strftime() would be nice.

I have a lot of timestamped things that I need to look at from day-to-day and it would make my job just a little bit easier if they were all in a standard format.

**Comment by tombruijn** [comment]
@JimmySticks2001 feature requests can be submitted on the [feature issue tracker](https://github.com/meskyanichi/backup-features/issues)

About your suggestion. Currently it's using the UTC timezone [to create a timestamp](https://github.com/meskyanichi/backup/blob/dc848670eb239373b01286c25d01f6a2c7930672/lib/backup/model.rb#L262-L263). This is the most universal.

It should be doable to change this, but I'm not sure how extensive the work would be. There would be an additional global configuration called `timezone` or something with a default to "+00:00" and use that in `Time.now.getlocal(Backup::Config.timezone)`. Unfortunately I don't have the time right now to work on it, but feel free to pick it up.

About this feature request. If you really want this now I guess you can use this hack/workaround, but I don't think it cover everything because some things are logged directly after these instance variables are set and before the hook is called. So maybe only set the package time to avoid mismatching timezones? Or override [this method](https://github.com/meskyanichi/backup/blob/dc848670eb239373b01286c25d01f6a2c7930672/lib/backup/logger.rb#L187-L197) on the `Logger` class.

```ruby 
Model.new(:issue_641, 'Issue 641') do
  before do
    @started_at = Time.now.utc
    @time = package.time = started_at.strftime("%Y.%m.%d.%H.%M.%S")
  end

  after do
    @finished_at = Time.now.utc
  end

  # ...
end
```
